#!/bin/bash

# SQL commands
SQL_COMMANDS=$(cat <<EOF
CREATE DATABASE $DB_NAME;
\c $DB_NAME
CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';
GRANT ALL PRIVILEGES ON SCHEMA public TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO $DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO $DB_USER;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOF
)

# Execute SQL commands using psql
echo "$SQL_COMMANDS" | psql -v ON_ERROR_STOP=1 --username "postgres"

echo "Database '$DB_NAME' created and permissions granted to user '$DB_USER'."
